### ISSUE TITLE
Compatible on Windows?

### ISSUE THREAD

**Issue by baileyztsang** [Juyong/FacePSNet#1]
I'm getting the error, "Creating library build\temp.win-amd64-3.7\Release\gen_normal_mask.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\gen_normal_mask.cp37-win_amd64.exp
gen_normal_mask.obj : error LNK2001: unresolved external symbol "public: long * __cdecl at::Tensor::data_ptr<long>(void)const " (??$data_ptr@J@Tensor@at@@QEBAPEAJXZ)
build\lib.win-amd64-3.7\gen_normal_mask.cp37-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120" when trying to setup.py in gen_normal_mask. Could this be a compatibility issue or am I missing something? Thank you!

**Comment by XYWang-coder** [comment]
Do you compile the code on the windows system? Since our code is compiled on ubuntu system, if you use windows system, there may be compilation errors. If possible, I suggest you to configure it on ubuntu system.

**Comment by baileyztsang** [comment]
I just tried running the code on ubuntu and now I'm having a problem compiling view_depth.cpp:

/usr/bin/ld: /tmp/cc65CpYA.o: in function `main':
view_depth.cpp:(.text.startup+0x12c): undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status

Any ideas what this could be? Thank you again!

**Comment by XYWang-coder** [comment]
This error is related to the link of the opencv library. If you have your opencv installed under /usr/local/include &amp; /usr/local/bin this error may not arise.



------------------&nbsp;Original message&nbsp;------------------
From: "baileyztsang"; 
Sendtime: Thursday, Jul 16, 2020 2:13 PM
To: "Juyong/FacePSNet"; 
Cc: "雪娃娃"<547819233@qq.com>; "Comment"; 
Subject: Re: [Juyong/FacePSNet] Compatible on Windows? (#1)





 
I just tried running the code on ubuntu and now I'm having a problem compiling view_depth.cpp:
 
/usr/bin/ld: /tmp/cc65CpYA.o: in function main': view_depth.cpp:(.text.startup+0x12c): undefined reference to cv::imread(std::__cxx11::basic_string<char, std::char_traits, std::allocator &gt; const&amp;, int)'
 collect2: error: ld returned 1 exit status
 
Any ideas what this could be? Thank you again!

**Comment by baileyztsang** [comment]
Got it! I'm running the code now on my own subjects but my output normal doesn't look nearly as good as the one from the sample image set. Could this be a problem with the position of my lights or the quality of my camera?

**Comment by XYWang-coder** [comment]
The lighting conditions in our datasets are mainly in front of people, at front right top and front left top, so if your lighting condition deviates from these three approximate directions it will have a certain impact on the result.



------------------&nbsp;Original message&nbsp;------------------
From: "baileyztsang"; 
Sendtime: Wednesday, Aug 5, 2020 12:18 PM
To: "Juyong/FacePSNet"; 
Cc: "雪娃娃"<547819233@qq.com>; "Comment"; 
Subject: Re: [Juyong/FacePSNet] Compatible on Windows? (#1)





 
Got it! I'm running the code now on my own subjects but my output normal doesn't look nearly as good as the one from the sample image set. Could this be a problem with the position of my lights or the quality of my camera?
