### ISSUE TITLE
landmarks on 3D mesh

### ISSUE THREAD

**Issue by zengxianyu** [Juyong/FacePSNet#2]
Hello, I saw in your paper that there is a loss between detected 2D landmark position and the corresponding vertex location in the 3D mesh. How can this correspondence be found? Did you label the landmarks on mesh manually?

**Comment by YudongGuo** [comment]
Yes, we label the landmarks on mesh manually.

**Comment by zengxianyu** [comment]
Could you please share the landmarks you labeled?

**Comment by YudongGuo** [comment]
Hi, the following  numbers are the indices of 51 vertices corresponding to the facial landmarks in the picture.

27409 28103 28493 28698 28865 29604 29770 29978 30372 31073 8162 8178 8188 8193 6516 7244 8205 9164 9884 2216 3887 4921 5829 4802 3641 10456 11354 12384 14067 12654 11493 5523 6026 7496 8216 8936 10396 10796 9556 8837 8237 7637 6916 5910 7385 8224 9065 10538 8830 8230 7630

![image](https://user-images.githubusercontent.com/28282620/89409117-1bb08780-d754-11ea-9dda-45b77f3919fd.png)
